---
title: "EDA_4,11,15,16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
4: Caring/Helping non-household members (t040101:t049999)
11: Eating/Drinking
15: Volunteer
16: Telephone Calls

#LOADING DATA
```{r Loading data}
library("plyr")
require(dplyr)
require(ggplot2)
data<-read.csv("atussum_0317.csv")
head(data)
data2 <- data.frame(month = substr(data[, 1], 5, 6),
                     age = data $ TEAGE,
                     year = data $ TUYEAR,
                     sex = ifelse(data $ TESEX == 1, "M", "F"))
```

#Splitting up into my variables
```{r}
library("plyr")
require(dplyr)
require(ggplot2)
head(data)
tail(data)
care <- data[, grep("^t04", names(data))]
eat <- data[, grep("^t11", names(data))]
volunteer <- data[, grep("^t15", names(data))]
phone <- data[, grep("^t16", names(data))]

data2 $ care <- rowSums(care)
data2 $ eat <- rowSums(eat)
data2 $ volunteer <- rowSums(volunteer)
data2 $ phone <- rowSums(phone)

head(data2)
```

#Some phone plots
```{r}
phoneMeans <- ddply(data2,.(year,month),summarise,
               mean=mean(phone))

 ggplot(phoneMeans, aes(x =year, y=mean, fill=month)) + 
   geom_bar(position=position_dodge(0.9), colour="black", stat="identity", width=0.9)+
   theme_bw()
 
phoneMeans$time <- 1:180
 ggplot(phoneMeans, aes(x =time, y=mean)) + 
   geom_line(position=position_dodge(0.9), colour="black", stat="identity", width=0.9)+
   theme_bw()
 
```


#General Variable against time plots
```{r}

currentMeans <- ddply(data2,.(year,month),
               numcolwise(mean))

#ggplot(currentMeans, aes(x =year, y=care, fill=month)) + 
   #geom_bar(position=position_dodge(0.9), colour="black", stat="identity", width=0.9)+
  # theme_bw()

ggplot() + geom_smooth(data=data2, aes(x = year, y = phone),size=1.3,fill ="pink2") + geom_point()
ggplot() + geom_smooth(data=data2, aes(x = year, y = eat),size=1.3,fill ="pink2") + geom_point()
ggplot() + geom_smooth(data=data2, aes(x = year, y = care),size=1.3,fill ="pink2") + geom_point()
ggplot() + geom_smooth(data=data2, aes(x = year, y = volunteer),size=1.3,fill ="pink2") + geom_point()
```
